version: '8'
services:

  #server:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    #ports:
    #  - "8888:8888"
    #volumes:
    #  - .:/app
    #  - /usr/local/cuda:/usr/local/cuda   # Mount CUDA toolkit to access GPU#
#
    #environment:
    #  - PYTHONUNBUFFERED=1
    #  - PYTHONDONTWRITEBYTECODE=1
    #  - CUDA_VISIBLE_DEVICES=all          # Use all available GPUs
    #depends_on:
    #  - vectorDB

  vectorDB:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: rag
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always


volumes:
    postgres_data: {}
