services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /mnt/c/Users/jarek/Desktop/rag/server_data:/server_data:rw
      - .:/server
      - ../models:/server/models
      - ./database:/server/database
      - /usr/local/cuda:/usr/local/cuda # Mount CUDA toolkit to access GPU
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      - CUDA_VISIBLE_DEVICES=all # Use all available GPUs
      - PGVECTOR_HOST=vectorDB
    depends_on:
      - vectorDB

  vectorDB:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vectordb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data:
